# Special thanks to @BrightRan over at https://github.com/orgs/community/discussions/26238 

name: Docker Image Building and Pushing to DockerHub
on:
  workflow_run:
    workflows: ["Node.js CI Building"]
    types:
      - completed

jobs:
  docker_build:
  if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # Docker is part of Ubuntu
    runs-on: ubuntu-latest

    steps:
    # No need to use actions/checkout, see: https://github.com/marketplace/actions/build-and-push-docker-images#git-context

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_TICKFRONTEND }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ejjvandelaar/tick-frontend:latest