# Special thanks to @BrightRan over at https://github.com/orgs/community/discussions/26238 

name: Docker Image Building and Pushing to DockerHub
on:
  workflow_run:
    workflows: ["Node.js CI Building"]
    types:
      - completed

jobs:
  docker_build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.semvers.outputs.patch }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
      #- name: Get Latest Tag
      #  id: previous-tag
      #  uses: WyriHaximus/github-action-get-previous-tag@v1
      #  with:
      #    fallback: latest

      #- uses: mr-smithers-excellent/docker-build-push@v5
      #  name: Build & Push Docker image
      #  with:
      #    image: ejjvandelaar/tick-frontend
      #    registry: docker.io
      #    tags: ${{ steps.previous-tag.outputs.tag }}
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_PASSWORD }} 
