# Special thanks to @BrightRan over at https://github.com/orgs/community/discussions/26238 

name: Docker Image Building and Pushing to DockerHub
on:
  workflow_run:
    workflows: ["Node.js CI Building"]
    types:
      - completed

jobs:
  docker_build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get latest version of project
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: code-syl/tick-frontend  # The repository to scan.
          #releases-only: true 
        id: versioning  # The step ID to refer to later.

      - run: echo "The current version is ${{ steps.versioning.outputs.tag }}"
    
      - name: Checkout
        uses: actions/checkout@v3

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & Push Docker image
        with:
          image: ejjvandelaar/tick-frontend
          registry: docker.io
          tags: ${{ steps.versioning.outputs.tag }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
