name: Docker Image Building and Pushing to DockerHub
on:
  workflow_run:
    workflows: ["Node.js CI Building"]
    types:
      - completed

jobs:
  docker_build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: latest # Optional fallback tag to use when no tag can be found

      - name: Build & Push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5        
        with:
          image: ejjvandelaar/tick-frontend
          registry: docker.io
          tags: ${{ steps.previoustag.outputs.tag }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
