# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI Building

on:
  push:
    branches: [ "main" ] # direct pushing should be disabled, this is just in case
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # Special thanks to Cory Rylan from https://coryrylan.com/blog/building-angular-cli-projects-with-github-actions for providing the answer to Chrome usage in the GitHub CLI

    steps:
    - uses: actions/checkout@v3
    
    - name: Caching node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install, Build and Test
      run: |
        npm ci
        npm run build:ci

  versioning:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - uses: phish108/autotag-action@1.1.51
      id: newtag
      with:
        github-token: ${{ secrets.GITHUB_TOKEN}}
        with-v: true

    - name: Debug
      run: |
        echo "${{ steps.newtag.outputs.tag }}"
        echo "${{ steps.newtag.outputs.new-tag }}"

  release:
    runs-on: ubuntu-latest
    needs: [build, versioning]
    
    steps:
    - uses: actions/checkout@v3

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.newtag.outputs.new-tag }}

